name: Unit tests on main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: npm config rm proxy
             npm config rm https-proxy
             unset HTTP_PROXY
             unset HTTPS_PROXY
             unset http_proxy
             unset https_proxy
             npm ci
      - name: Run unit tests
        run: npm run test
